---
- hosts: all
  connection: local
  remote_user: ansible
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Run Docker setup
      ansible.builtin.import_tasks: roles/docker/main.yml
